### ISSUE TITLE
设置Timeout

### ISSUE THREAD

**Issue by ghost** [JixunMoe/proxy-163#1]
Proxy hang up, try another one 只对error有效, 很多没有error但卡在那里了
对于timeout大于一定值的proxy自动换下一个

我试着在handleChinaProxy中加入类似的：

```
 req.setTimeout(1000, () => {
    if (count === undefined) {
      count = 3;
    }

    if (count-- === 0) {
      console.info('[!] Proxy hang up, try another one.');
      response.end();
    } else {
      handleChinaProxy(request, response, count);
    }
  });
```

但是这样handle timeout会有问题

我是使用 `youtube-dl http://music.163.com/#/album?id=25393 --proxy localhost:4003 --get-url` 来测试的
没有办法跑下整个album的url

**Comment by jixunmoe** [comment]
这个工具可以收到错误信息后重试吗？如果可以的话，那么可以砍掉通信然后重新找一个代理。

**Comment by jixunmoe** [comment]
另外这个代理是专门给获取音乐资源的链接设计的.. 刚才抓了下请求发现

```
[*] Proxy url http://music.163.com/api/album/25393?id=25393
[*] Proxy via 122.193.14.114
[*] Proxy url http://music.163.com/api/song/detail?ids=%5B254170%5D&id=254170
[*] Proxy via 120.198.231.24
```

等一下看看到底是什么问题..

**Comment by jixunmoe** [comment]
感觉应该是运气问题，等下把读取代理 ip 的代码改改，改成从列表读取。

**Comment by jixunmoe** [comment]
我在最新的 commit: https://github.com/JixunMoe/proxy-163/commit/cd1513eaf445d74dd131364dedcd113812524f84 改成了从 `proxies.txt` 读取代理设定，你可以找工具批量测试代理，进行二次过滤，把不稳定的代理剔除掉。

**Comment by ghost** [comment]
从 proxies.txt 读取代理设定 并没有解决实质问题
感觉还是由于proxy没有正确处理timeout造成的

```
youtube-dl http://music.163.com/\#/album\?id\=25393 --proxy localhost:4003 --get-url
http://115.231.74.139/m1.music.126.net/4cg9SjR0Hv2dj85OaIX4RA==/990659976633814.mp3
http://115.231.74.139/m1.music.126.net/Iy51Lsp6YxwKVVvCVuLM0w==/990659976633818.mp3
```

之前没设置timeout，通过代理获得上面两个地址花了好久

最新的commit里把timeout时间从15000改成1500来测试的
error还是由于timeout的callback函数引起的我感觉

```
[*] Proxy url http://music.163.com/api/album/25393?id=25393
[*] Proxy via 36.251.248.183:3128
[!] Proxy hang up, try another one.
[*] Proxy via 120.198.231.22:81
[!] Proxy hang up, try another one.
[*] Proxy via 27.115.75.114:8080
[!] Proxy hang up, try another one.
[*] Proxy via 218.106.96.198:83
events.js:142
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:423:15)
    at IncomingMessage.<anonymous> (/Users/yielder/proxy-163/src/proxy.js:176:16)
    at emitOne (events.js:78:13)
    at IncomingMessage.emit (events.js:170:7)
    at readableAddChunk (_stream_readable.js:147:16)
    at IncomingMessage.Readable.push (_stream_readable.js:111:10)
    at HTTPParser.parserOnBody (_http_common.js:110:22)
    at Socket.socketOnData (_http_client.js:312:20)
    at emitOne (events.js:78:13)
    at Socket.emit (events.js:170:7)
```

**Comment by ghost** [comment]
感觉有点类似于http://stackoverflow.com/questions/24667122/http-request-timeout-callback-in-node-js

**Comment by ghost** [comment]
#2

**Comment by jixunmoe** [comment]
虽然没有实质上解决问题，但这是我会的部分了。我不是网络工程师，不懂怎么去优化..

代理列表获取的地址如果是没有问题的话，那么这个脚本也不会有问题。例如下面这种情况，代理要求登录认证之类的，返回代码也是 200，无法判定。

``` text
[*] Proxy via 119.255.59.162:80
<HTML><meta http-equiv="Content-Type" content="text/html; charset=gb2312"></meta><body bgcolor='#ffffff'></body><script language="JavaScript">var localHref = "https://119.255.59.162:8443";top.location.replace(localHref);</script></HTML>
```

我在最新的 commit 再改了下，如果域名是 music.163.com 则不走代理直接访问。解析下载地址并不需要代理，~~包括版权音乐~~。

你用的 `youtube-dl` 这个软件会抓取 4 个可能有效的地址进行检测 (猜测, 没有细读)，经过该脚本代理，遇到有问题的代理只是时间问题。

另外你可以不走代理下载，不过有部分曲目会无法下载到 (具体规律未知)， `extractor/neteasemusic.py` 的 `NetEaseMusicBaseIE.extract_formats` 方法修改如下：

``` py
    def extract_formats(self, info):
        formats = []
        for song_format in self._FORMATS:
            details = info.get(song_format)
            if not details:
                continue
            song_file_path = '/%s/%s.%s' % (
                self._encrypt(details['dfsId']), details['dfsId'], details['extension'])

            song_url = 'http://p2.music.126.net' + song_file_path
            formats.append({
                'url': song_url,
                'ext': details.get('extension'),
                'abr': float_or_none(details.get('bitrate'), scale=1000),
                'format_id': song_format,
                'filesize': details.get('size'),
                'asr': details.get('sr')
            })
        return formats
```

当然，如果你有更好的网络优化方案你也可以写出来，我可以合并进来。

照着你给的链接实现了“当发生错误/超时时只调用一次错误回调”，然而你也扔了个 PR _(:3__

**Comment by ghost** [comment]
嗯。。我也不打算折腾了。。。
好多歌不挂代理都会 access denied 没法下载，这个代理 还是 相当好用 :smile:  :+1: 
多谢啦

**Comment by jixunmoe** [comment]
能下，走 `p*` 的域名。你给的那个例子，走这个域名可以免代理直接下载。目测是版权音乐不能走这个路线。

不得不吐槽一下 `youtube-dl` 的下载方式，解析错误不会跳过解析而是直接报错强制终止..
